name: Main - Test, Build, and Deploy

on:
  push:
    branches:
      - main
      - axon-4

jobs:
  build:
    name: Test and Build on JDK ${{ matrix.java-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - java-version: 17
            deploy-enabled: true
          - java-version: 21
            deploy-enabled: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4.7.1
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java-version }}
          cache: "maven"
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Import GPG key
        if: matrix.deploy-enabled
        run: |
          echo "${{ secrets.SONATYPE_GPG_KEY }}" | base64 --decode | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
        env:
          GPG_TTY: $(tty)

      - name: Test and Build
        run: |
          ./mvnw -B -U -Dstyle.color=always -Possrh clean verify

      - name: Deploy to Sonatype
        if: matrix.deploy-enabled
        run: |
          ./mvnw -B -U -Dstyle.color=always -Prelease -Psign deploy -DskipTests=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_USERNAME: ${{ secrets.SONATYPE_TOKEN_ID }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_TOKEN_PASS }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.SONATYPE_GPG_PASSWORD }}
