name: PR - Test and Build

on:
  pull_request:

jobs:
  build:
    name: Test and Build on JDK ${{ matrix.java-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - java-version: 17
          - java-version: 21
      fail-fast: false # run both to the end

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4.0.0
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java-version }}
          cache: "maven"
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Test and Build
        run: |
          ./mvnw -B -U -Dstyle.color=always -Possrh clean verify
